### PR TITLE
Fix the broken link for the slide templates

### PR DESCRIPTION
**Pull request by ildikov**
Signed-off-by: Ildiko Vancsa <ildiko.vancsa@gmail.com>

### CODE REVIEW

**Comment by gcutrini** [comment]
Hi @ildikov, I can access the linked files from the following paths:
https://deploy-preview-74--starlingx-io.netlify.com/collateral/StarlingX_SlideDeck_Template_a.key
https://deploy-preview-74--starlingx-io.netlify.com/collateral/StarlingX_SlideDeck_Template_a.pptx

So the markdown to be used in the FAQ's page should be:
`[Keynote](/collateral/StarlingX_SlideDeck_Template_a.key)`
`[PowerPoint](/collateral/StarlingX_SlideDeck_Template_a.pptx)`

Thanks!

**Comment by jimmytipit** [comment]
Ildiko - take a look at @gcutrini's comment:

So the markdown to be used in the FAQ's page should be:
[Keynote](/collateral/StarlingX_SlideDeck_Template_a.key)
[PowerPoint](/collateral/StarlingX_SlideDeck_Template_a.pptx)

**Comment by ildikov** [comment]
Removed the extra 'templates/' from the path that I accidentally left there. Hope it works now.

**Comment by ildikov** [comment]
Thanks.

If you see the "typo" please point it out directly next time as it took me a while to realize what the issue is. :)

**Pull request merged**
