### PR TITLE
Adding the second blog post in the PTP series

### PR DESCRIPTION
**Pull request by ildikov**
This patch adds the second blog post of the PTP series including
the screen shots that are used to describe how to configure PTP
on StarlingX.

Signed-off-by: Ildiko Vancsa <ildiko.vancsa@gmail.com>

### CODE REVIEW

**Comment by ildikov** [comment]
DO NOT MERGE YET!

**Comment by ildikov** [comment]
Blog post is scheduled to be published on Monday (May 17)!

**Review by jimmytipit — APPROVED** [review]
LGTM

**Comment by ildikov** [comment]
Checked the preview and formatting looks good. Content was reviewed by the contributor as well.

**Pull request merged**
